config/routes.rb
Rails.application.routes.draw do
  get 'user/index' => 'user#index'
  get 'photo/index/:id' => 'photo#index', as: 'user_photos'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all

  end

  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photosite05</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
      img {
          max-width: 40%;
          max-height: 20%;
      }
  </style>
  <form>
    <input type="button" value="Go back!" onclick="history.back()" align="right">
  </form>
  <title> PHOTOSITE </title>
</head>
<body bgcolor="#faebd7">
<div>
  <h1>
    <center>Photosite</center>
  </h1>
  <h3>
    <center><i>User Photo Page</i></center>
  </h3>
</div>
<div>
  <center>
    <h1>Photos of <%= @user.first_name %> <%= @user.last_name %></h1>
  </center>
  <% @photos.each do |photo| %>
    <center>
      <img src="<%= photo.file_url %>">
      <div>Photo Created at <%= photo.date_time %></div>
    </center>

    <% @comments.where("photo_id=?", photo.id).each do |comment| %>
      <li>
        <div>
          <p>
          <center>Comment: <%= comment.comment %></center>
          </p>
          <p>
          <center>Created at: <%= comment.date_time %></center>
          </p>
          <p>
          <center>Posted by: <%= link_to display_name(comment.user_id), user_photos_path(comment.user_id) %></center>
          </p>
        </div>
      </li>
    <% end %>
    </div>
    <br>
  <% end %>
  </body>
</html>

app/views/user/index.html.erb
<!DOCTYPE html>
<html>
<h1>Welcome to the photo hub</h1>
<head>
  <style>
      body {
          background-color: lavenderblush
      }

      h3 {
          color: navy
      }

      p {
          color: cornflowerblue
      }

      h1 {
          text-shadow: 2px 2px;
      }

      td {
          align-items: center
      }

      table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
          padding: 20px
      }

      table {
          width: 30%;
          backdrop-filter: opacity(40%)
      }
  </style>
</head>
<body bgcolor="#e6e6fa">
<h3><i>There are 6 users in this group</i></h3>
<table>
  <thead>
  <tr>
    <th><h2>Index</h2></th>
    <th><h2>First</h2></th>
    <th><h2>Last</h2></th>
  </tr>
  </thead>
    <% @users.map  do |user| %>
    <tr>
      <td><%= link_to user.id, user_photos_path(user.id) %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
    </tr>
  <% end %>
</table>
</body>
</html>